### ISSUE TITLE
Implement Board Members Section with Profile Links

### ISSUE THREAD

**Issue by prernamittal** [ACMW-Manipal/acmw-website-24#1]
## Description
The ACMW Manipal website currently lacks a dedicated page to showcase our board members. Let's create a new page where we can display profile pictures and descriptions of our board members.

## Tasks
- Design the layout for the board members on the Home Page ie `index.html`.
- Implement a grid or horizontal list layout to display profile pictures and names.
- Profile details (e.g., name, role, bio).

Comment under this issue to assign this task to yourself!

**Comment by shravanibhor** [comment]
I can take this issue

**Comment by prernamittal** [comment]
> I can take this issue.

Sure, go ahead!

**Comment by Prriya-Karn** [comment]
@prernamittal please assign this issue to me
