### ISSUE TITLE
fix the navbar at the top of all pages

### ISSUE THREAD

**Issue by shrial** [ACMW-Manipal/acmw-website-24#19]
try to position the navbar at the top so that it remains fixed at the top of the screen even while the user scrolls

**Comment by shrial** [comment]
could you please assign this to me, i would like to work on this issue

**Comment by prernamittal** [comment]
> could you please assign this to me, I would like to work on this issue

Sure, go ahead!

**Comment by Prriya-Karn** [comment]
please assign this issue to me
