### ISSUE TITLE
Fix Recruitment Page

### ISSUE THREAD

**Issue by prernamittal** [ACMW-Manipal/acmw-website-24#23]
![image](https://github.com/ACMW-Manipal/acmw-website-24/assets/93262556/fb056379-3f3b-4b76-bfeb-16de084de2f0)

Currently the UI of this page is not consistent in terms of color scheme and navbar with the rest of the website pages. Make changes to `join.html` page to fix this issue and also style the CSS accordingly.

**Comment by JuanitaCathy** [comment]
hello! I fixed this and thought of adding it with my navbar pr since I missed the color scheme on this..
do i create a separate pr or just add it with my navbar pr?

**Comment by prernamittal** [comment]
> hello! I fixed this and thought of adding it with my navbar pr since I missed the color scheme on this.. do i create a separate pr or just add it with my navbar pr?

If you have already fixed then no problem you don't need to create a separate PR.
