### ISSUE TITLE
Bug in Event Page - Navbar Covers Content

### ISSUE THREAD

**Issue by swetha3456** [ACMW-Manipal/acmw-website-24#39]
![Screenshot 2024-04-13 133328](https://github.com/ACMW-Manipal/acmw-website-24/assets/116883043/7e1e7a86-66b0-4d97-9417-6849fbcff504)

The heading has been cut off by the navbar. Please assign this issue to me.

**Comment by Prriya-Karn** [comment]
@prernamittal please assign this issue to me
