### ISSUE TITLE
Add Social Media Icons with Links

### ISSUE THREAD

**Issue by prernamittal** [ACMW-Manipal/acmw-website-24#4]
## Description
The ACMW Manipal website currently lacks correct social media icons and links to our Instagram, WhatsApp, and LinkedIn accounts. Let's enhance the website by adding these icons in the footer or header for easy access to our social media platforms.

## Tasks
-  Choose appropriate social media icons (e.g., Instagram, WhatsApp, LinkedIn). Use FontAwesome 
- Obtain official URLs for ACMW Manipal's Instagram, WhatsApp, and LinkedIn accounts.
- Implement the icons and corresponding links in `index.html' file footer section.

Comment under this issue to assign this task to yourself!

**Comment by swetha3456** [comment]
Hi, I would like to work on this issue. Please assign it to me.

**Comment by prernamittal** [comment]
> @prernamittal please assign this issue to me

Sure, go ahead with this one first!

**Comment by Prriya-Karn** [comment]
@prernamittal I sent the PR, Please review :)
