### ISSUE TITLE
Implement Shades of Blue Color Scheme

### ISSUE THREAD

**Issue by prernamittal** [ACMW-Manipal/acmw-website-24#5]
## Description
The ACMW Manipal website needs a cohesive colour scheme to enhance its visual appeal and branding. Let's implement a color scheme using shades of blue throughout the website.

##Tasks
- Choose a primary shade of blue as the base color for the website.
- Define complementary shades of blue for various elements such as headers, text, buttons, and backgrounds.
- Ensure the change is consistent throughout the website across all pages and ensure the readability.

Comment under this issue to assign this task to yourself!

**Comment by swetha3456** [comment]
Hi, I would like to work on this. Please assign it to me.

**Comment by prernamittal** [comment]
> Hi, I would like to work on this. Please assign it to me.

Sure! Go ahead!
