### ISSUE TITLE
Implement Member Names and Achievements Section

### ISSUE THREAD

**Issue by prernamittal** [ACMW-Manipal/acmw-website-24#6]
## Description
The ACMW Manipal website should showcase the names of active members along with their notable achievements to highlight their contributions and inspire others. Let's implement a dedicated section to display member names and achievements on the website.

## Tasks
- Design the layout for displaying member names and achievements on `index.html` page.
- Create a data structure (e.g., array, object) to store member information including names and achievements.
- Implement logic to dynamically populate the section with member details retrieved from the data structure.

Comment under this issue to assign this task to yourself!

**Comment by Prriya-Karn** [comment]
@prernamittal  please assign this issue to me

**Comment by prernamittal** [comment]
> @prernamittal please assign this issue to me

You can go ahead with this one!

**Comment by Prriya-Karn** [comment]
And can I add react library in this project?..

**Comment by Prriya-Karn** [comment]
I sent the PR please review it :)
