### ISSUE TITLE
Implement Features on Recruitment Page

### ISSUE THREAD

**Issue by prernamittal** [ACMW-Manipal/acmw-website-24#7]
## Description
The recruitment page on the ACMW Manipal website needs a form and prominent "Apply Now" button to encourage interested individuals to apply for membership or participation. Let's enhance the recruitment page by adding this button and implementing additional features to streamline the application process.

## Tasks
- Design and integrate an eye-catching "Apply Now" button on the recruitment page ie `join.html`
- Implement functionality to capture user information (e.g., name, email, area of interest) upon clicking the button.
- Create a form or modal window for applicants to fill out and submit their details.
- Ensure validation and error handling for the application form to improve user experience.

Comment under this issue to assign this task to yourself!

**Comment by JuanitaCathy** [comment]
i'd like to work on this

**Comment by prernamittal** [comment]
> i'd like to work on this

Sure, go ahead!

**Comment by JuanitaCathy** [comment]
Oh, it was mentioned in the tasks to implement it in join.html

**Comment by prernamittal** [comment]
> Oh, it was mentioned in the tasks to implement it in join.html

yaya sorry my bad it's `join.html`

**Comment by JuanitaCathy** [comment]
I think there is currently a merge conflict due to style.css. Style.css got merged recently and it didn't update in my vscode yet. What do i do ;/

**Comment by JuanitaCathy** [comment]
okay! can you review the PR?

**Comment by prernamittal** [comment]
> okay! can you review the PR?

Hey this looks good to me. When you're submitting a PR always mention which Issue it resolves. So you can add "closes Issue #7" in your PR description! Kudos!

**Comment by JuanitaCathy** [comment]
thanks! yea i did add the issue number

> > okay! can you review the PR?
> 
> Hey this looks good to me. When you're submitting a PR always mention which Issue it resolves. So you can add "closes Issue #7" in your PR description! Kudos!
