### ISSUE TITLE
Implement "About Us" Page

### ISSUE THREAD

**Issue by prernamittal** [ACMW-Manipal/acmw-website-24#8]
## Description
The ACMW Manipal website requires an engaging and informative "About Us" page to provide visitors with an overview of our organization, mission, vision, and values. Let's create a dedicated "About Us" page that accurately represents ACMW Manipal and its objectives.

## Tasks
- Design the layout for the "About Us" page ie `about.html`, including sections for mission, vision, values, and organization overview.
- Write compelling content to describe ACMW Manipal's background, goals, and impact.
- Include relevant images or graphics to enhance the visual appeal of the page.

Comment under this issue to assign this task to yourself!

**Comment by shravanibhor** [comment]
I can work on this issue.

**Comment by prernamittal** [comment]
> I can work on this issue.

Sure! start working on this issue first!
